// const { faker } = require('@faker-js/faker');
// // import { describe, it, expect } from 'vitest';
// // import { faker } from '@faker-js/faker/locale/en';

// exports.seed = function(knex) {
//   // Deletes ALL existing entries
//   return knex('teachers').del()
//     .then(function () {
//       // Inserts seed entries
//       let teachers = [];
//       for(let i = 1; i <= 25; i++){
//         teachers.push({
//           teacher_id: i,
//           name: faker.person.fullName(),
//           age: faker.number.int({min:24, max:60}),
//           specialization: faker.person.jobTitle(),
//           experience: faker.number.int({min:1, max:20}),
//           rating: faker.number.int({min:1, max:5, precision: 0.1}),
//         //   latitude: faker.address.latitude(),
//         //   longitude: faker.address.longitude(),
//         //   city: faker.location.city(),
//           country: faker.location.country()
//         });
//       }
//       return knex('teachers').insert(teachers);
//     });
// };

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("teachers").del();
  await knex("teachers").insert([
    {
      teacher_id: 1,
      name: "Hazel Bartell",
      age: 36,
      specialization: "Math",
      teaching_level: "High School",
      experience: 7,
      rating: 3.0,
      province: "Ontario",
      city: "Toronto",
    },
    {
      teacher_id: 3,
      name: "Caleb Kuhn",
      age: 25,
      specialization: "Biology",
      teaching_level: "Elementary",
      experience: 3,
      rating: 5.0,
      province: "Ontario",
      city: "Toronto",
    },
    {
      teacher_id: 5,
      name: "Zara Runolfsdottir",
      age: 42,
      specialization: "Computer Science",
      teaching_level: "University",
      experience: 12,
      rating: 4.5,
      province: "Ontario",
      city: "Toronto",
    },
    {
      teacher_id: 7,
      name: "Nadia Sporer",
      age: 29,
      specialization: "Physics",
      teaching_level: "Middle School",
      experience: 6,
      rating: 4.2,
      province: "Alberta",
      city: "Calgary",
    },
    {
      teacher_id: 9,
      name: "Emilio Effertz",
      age: 31,
      specialization: "Chemistry",
      teaching_level: "High School",
      experience: 9,
      rating: 4.8,
      province: "British Columbia",
      city: "Vancouver",
    },
    {
      teacher_id: 11,
      name: "Leo Schneider",
      age: 37,
      specialization: "English",
      teaching_level: "University",
      experience: 14,
      rating: 4.6,
      province: "Quebec",
      city: "Montreal",
    },
    {
      teacher_id: 13,
      name: "Ethan Boyle",
      age: 33,
      specialization: "History",
      teaching_level: "High School",
      experience: 10,
      rating: 4.7,
      province: "Ontario",
      city: "Ottawa",
    },
    {
      teacher_id: 15,
      name: "Ella Rodriguez",
      age: 28,
      specialization: "Geography",
      teaching_level: "Middle School",
      experience: 5,
      rating: 4.3,
      province: "Quebec",
      city: "Quebec City",
    },
    {
      teacher_id: 17,
      name: "Mia Kulas",
      age: 39,
      specialization: "French",
      teaching_level: "High School",
      experience: 16,
      rating: 4.9,
      province: "Alberta",
      city: "Edmonton",
    },
    {
      teacher_id: 19,
      name: "Scarlett Mann",
      age: 41,
      specialization: "Chemistry",
      teaching_level: "University",
      experience: 18,
      rating: 4.8,
      province: "British Columbia",
      city: "Victoria",
    },
    {
      teacher_id: 21,
      name: "Amelia Hammes",
      age: 34,
      specialization: "Computer Science",
      teaching_level: "University",
      experience: 10,
      rating: 4.5,
      province: "Ontario",
      city: "Toronto",
    },
    {
      teacher_id: 23,
      name: "Abigail Swift",
      age: 31,
      specialization: "Math",
      teaching_level: "High School",
      experience: 6,
      rating: 4.2,
      province: "Ontario",
      city: "Toronto",
    },
    {
      teacher_id: 25,
      name: "Emily Powlowski",
      age: 29,
      specialization: "English",
      teaching_level: "University",
      experience: 8,
      rating: 4.6,
      province: "Alberta",
      city: "Calgary",
    },
    {
      teacher_id: 27,
      name: "Nadia Sporer",
      age: 36,
      specialization: "Chemistry",
      teaching_level: "Middle School",
      experience: 7,
      rating: 4.4,
      province: "British Columbia",
      city: "Vancouver",
    },
    {
      teacher_id: 29,
      name: "Sofia Lowe",
      age: 32,
      specialization: "Biology",
      teaching_level: "High School",
      experience: 9,
      rating: 4.7,
      province: "Quebec",
      city: "Montreal",
    },
    {
      teacher_id: 31,
      name: "Avery Nikolaus",
      age: 38,
      specialization: "Physics",
      teaching_level: "Middle School",
      experience: 11,
      rating: 4.9,
      province: "Ontario",
      city: "Ottawa",
    },
    {
      teacher_id: 33,
      name: "Liam Wuckert",
      age: 37,
      specialization: "History",
      teaching_level: "High School",
      experience: 12,
      rating: 4.8,
      province: "Quebec",
      city: "Quebec City",
    },
    {
      teacher_id: 35,
      name: "James Gerhold",
      age: 30,
      specialization: "Geography",
      teaching_level: "Middle School",
      experience: 5,
      rating: 4.3,
      province: "Alberta",
      city: "Edmonton",
    },
    {
      teacher_id: 37,
      name: "Lucas Schoen",
      age: 35,
      specialization: "French",
      teaching_level: "High School",
      experience: 13,
      rating: 4.6,
      province: "British Columbia",
      city: "Victoria",
    },
    {
      teacher_id: 39,
      name: "Michaela Robel",
      age: 33,
      specialization: "Chemistry",
      teaching_level: "University",
      experience: 15,
      rating: 4.9,
      province: "Ontario",
      city: "Toronto",
    },
    {
      teacher_id: 41,
      name: "Riley Spinka",
      age: 36,
      specialization: "English",
      teaching_level: "University",
      experience: 14,
      rating: 4.8,
      province: "Quebec",
      city: "Montreal",
    },
    {
      teacher_id: 43,
      name: "Jackson Haag",
      age: 29,
      specialization: "Math",
      teaching_level: "High School",
      experience: 7,
      rating: 4.5,
      province: "Alberta",
      city: "Calgary",
    },
    {
      teacher_id: 45,
      name: "Levi Batz",
      age: 32,
      specialization: "Biology",
      teaching_level: "Elementary",
      experience: 8,
      rating: 4.7,
      province: "British Columbia",
      city: "Vancouver",
    },
    {
      teacher_id: 47,
      name: "Lucas Homenick",
      age: 39,
      specialization: "Physics",
      teaching_level: "Middle School",
      experience: 9,
      rating: 4.6,
      province: "Quebec",
      city: "Quebec City",
    },
    {
      teacher_id: 49,
      name: "Henry Swaniawski",
      age: 31,
      specialization: "History",
      teaching_level: "High School",
      experience: 10,
      rating: 4.9,
      province: "Alberta",
      city: "Edmonton",
    },
  ]);
};
